### ISSUE TITLE
Uploading level it gets deleted

### ISSUE THREAD

**Issue by saimones34324** [iAndyHD3/image2gd#2]
When I try to upload a level using this mod, everything goes well until after a while, the level is deleted, I don't what happens, I mean when I want to check my level on the servers, it's deleted

**Comment by iAndyHD3** [comment]
This happens because Robtop added server side security to avoid people uploading nsfw images and stuff.

What you can try is once the image is imported in the editor, split all the objects a bit and then move them together with the move trigger. that way there will be less objects in a very small space which can increase chance of the servers not detecting it. I can't really do anything else

**Comment by saimones34324** [comment]
thank yuo i will try that
